baseURL = "https://lkummer.github.io/break/"
title = "Break SCSS"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "About"
    text = """
    Systemizing media queries is challenging.
    Break makes it easy.
    Originating from a well worn snippet, with testing and documentation added.
    Break aims to provide a high quality solution.
    """
  [params.seo]
    category = "Sass"
    downloadURL = "#"
    versionEnv = "npm_package_version"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Break Contributors"
  [params.colors]
    primary-600 = "hsl(340, 98%, 78%)"
    primary-500 = "hsl(340, 95%, 75%)"
    primary-400 = "hsl(340, 85%, 70%)"
    accent-600 = "hsl(170, 83%, 62%)"
    accent-500 = "hsl(170, 80%, 60%)"
    accent-400 = "hsl(170, 70%, 55%)"
    accent-300 = "hsl(216, 12%, 21%)"
    accent-200 = "hsl(216, 12%, 21%)"
    accent-100 = "hsl(216, 10%, 25%)"
    background-900 = "hsl(216, 10%, 15%)"
    background-400 = "hsl(216, 12%, 21%)"
    background-300 = "hsl(216, 12%, 21%)"
    background-200 = "hsl(216, 10%, 20%)"
    background-100 = "hsl(216, 10%, 12%)"
    text-900 = "hsla(0, 0%, 100%, 0.95)"
    text-800 = "hsla(0, 0%, 100%, 0.8)"
    text-700 = "hsla(0, 0%, 100%, 0.65)"
    text-500 = "hsla(170, 30%, 95%, 0.65)"
    text-400 = "hsla(170, 30%, 95%, 0.8)"
    text-300 = "hsla(170, 30%, 95%, 0.95)"
    text-200 = "hsla(0, 0%, 0%, 0.7)"
    text-100 = "hsla(0, 0%, 100%, 0.95)"
    highlight-inline = "hsl(340, 98%, 78%)"
    highlight-text = "hsl(216, 35%, 99%)"
    highlight-background = "hsl(216, 13%, 14%)"
    highlight-comment = "hsl(216, 25%, 55%)"
    highlight-special = "hsl(170, 75%, 55%)"
    highlight-operator = "hsl(340, 95%, 75%)"
    highlight-literal = "hsl(250, 80%, 70%)"
  [params.graphics]
    favicon = "favicon.svg"
    logo = """
    <svg class="navbar-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 40">
      <defs>
        <style>
          .navbar {
            --clip-shape: polygon(0 0, 100% 0, 100% 35%, 0 65%);
            --logo-bg-color: var(--color-primary-400);
          }
          .logo {
            transform: scale(0.7);
            transform-origin: 0px 18px;
          }
          .logo-bg {
            transition: fill 0.3s ease;
            fill: var(--logo-bg-color);
          }
          .logo-fg {
            fill: var(--color-accent-400);
            transition: clip-path 0.3s ease;
            clip-path: var(--clip-shape);
          }
          .navbar-logo-link:hover {
            --clip-shape: polygon(0 0, 100% 0, 100% 0, 0 0);
            --logo-bg-color: var(--color-primary-600);
          }
        </style>
      </defs>
      <path class="logo logo-bg" d="M32,12V8a8,8,0,0,0-8-8H0V40H24a8,8,0,0,0,8-8V28a8,8,0,0,0-8-8,8,8,0,0,0,8-8ZM18.5,34H8V23H18.5a5.5,5.5,0,0,1,0,11Zm0-17H8V6H18.5a5.5,5.5,0,0,1,0,11Z"/>
      <path class="logo logo-fg" d="M32,12V8a8,8,0,0,0-8-8H0V40H24a8,8,0,0,0,8-8V28a8,8,0,0,0-8-8,8,8,0,0,0,8-8ZM18.5,34H8V23H18.5a5.5,5.5,0,0,1,0,11Zm0-17H8V6H18.5a5.5,5.5,0,0,1,0,11Z"/>
    </svg>
    """

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/LKummer/break"
  [[menu.footer]]
    name = "Github"
    url = "https://github.com/LKummer/break"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
