baseURL = "https://lkummer.github.io/break/"
title = "Break SCSS"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "About"
    text = """
    Systemizing media queries is challenging.
    Break makes it easy.
    Originating from a well worn snippet, with testing and documentation added.
    Break aims to provide a high quality solution to the problem.
    """
  [params.seo]
    category = "Sass"
    downloadURL = "#"
    versionEnv = "npm_package_version"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Break Contributors"
  [params.colors]
    primary-600 = "hsl(340, 98%, 78%)"
    primary-500 = "hsl(340, 95%, 75%)"
    primary-400 = "hsl(340, 85%, 70%)"
    accent-600 = "hsl(170, 83%, 62%)"
    accent-500 = "hsl(170, 80%, 60%)"
    accent-400 = "hsl(170, 70%, 55%)"
    background-900 = "hsl(216, 10%, 15%)"
    background-200 = "hsl(216, 10%, 20%)"
    background-100 = "hsl(216, 10%, 12%)"
    text-900 = "hsla(0, 0%, 100%, 0.95)"
    text-800 = "hsla(0, 0%, 100%, 0.8)"
    text-700 = "hsla(0, 0%, 100%, 0.65)"
    text-200 = "hsla(0, 0%, 0%, 0.7)"
    text-100 = "hsla(0, 0%, 100%, 0.95)"
    highlight-text = "hsl(240, 35%, 99%)"
    highlight-background = "hsl(240, 13%, 14%)"
    highlight-comment = "hsl(250, 25%, 55%)"
    highlight-special = "hsl(180, 75%, 55%)"
    highlight-operator = "hsl(330, 95%, 75%)"
    highlight-literal = "hsl(250, 80%, 70%)"

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/LKummer/break"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
