name: Run tests and linters

on:
  push:
    branches:
      - master

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn run test
      - name: Run linters
        run: yarn run lint
